Imds:
  ImdsSupport: v2.0
Region: eu-north-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: m6i.4xlarge
  Networking:
    SubnetId: <<subnet-1234567890>> #MUST BE IN eun1-az2
    AdditionalSecurityGroups:
      - <<sg-1234567890>>
      - <<sg-1234567890>>
  DisableSimultaneousMultithreading: false
  Ssh:
    KeyName: <<MyKey>>
  SharedStorageType: Efs
  LocalStorage:
    RootVolume:
      Size: 100
      Encrypted: true
      VolumeType: gp3
      DeleteOnTermination: true
  Dcv:
    Enabled: true
    Port: 8443
    AllowedIps: 0.0.0.0/0
  CustomActions:
    OnNodeConfigured:
      Script: s3://<<YOUR_BUCKET>>/post-install.headnode.sh
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
    S3Access:
      - BucketName: '*'
        EnableWriteAccess: true
  Imds:
    Secured: True
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
    QueueUpdateStrategy: TERMINATE
    EnableMemoryBasedScheduling: true
  SlurmQueues:
    - Name: hpc7a
      CapacityType: ONDEMAND
      Networking:
        SubnetIds: 
          - <<subnet-1234567890>> #MUST BE IN eun1-az2
        AdditionalSecurityGroups:
          - <<sg-1234567890>>
          - <<sg-1234567890>>
        PlacementGroup:
          Enabled: true
      ComputeResources:
        - Name: hpc7a-96xlarge
          InstanceType: hpc7a.96xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
        - Name: hpc7a-48xlarge
          InstanceType: hpc7a.48xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
        - Name: hpc7a-24xlarge
          InstanceType: hpc7a.24xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
        - Name: hpc7a-12xlarge
          InstanceType: hpc7a.12xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      CustomActions:
        OnNodeConfigured:
          Script: s3://<<YOUR_BUCKET>>/post-install.compute.sh
    - Name: hpc6id
      CapacityType: ONDEMAND
      Networking:
        SubnetIds: 
          - <<subnet-1234567890>> #MUST BE IN eun1-az2
        AdditionalSecurityGroups:
          - <<sg-1234567890>>
          - <<sg-1234567890>>
        PlacementGroup:
          Enabled: true
      ComputeResources:
        - Name: hpc6id-32xlarge
          InstanceType: hpc6id.32xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      CustomActions:
        OnNodeConfigured:
          Script: s3://<<YOUR_BUCKET>>/post-install.compute.sh
    - Name: hpc6a
      CapacityType: ONDEMAND
      Networking:
        SubnetIds: 
          - <<subnet-1234567890>> #MUST BE IN eun1-az2
        AdditionalSecurityGroups:
          - <<sg-1234567890>>
          - <<sg-1234567890>>
        PlacementGroup:
          Enabled: true
      ComputeResources:
        - Name: hpc6a-48xlarge
          InstanceType: hpc6a.48xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      CustomActions:
        OnNodeConfigured:
          Script: s3://<<YOUR_BUCKET>>/post-install.compute.sh
    - Name: c5n
      CapacityType: ONDEMAND
      Networking:
        SubnetIds: 
          - <<subnet-1234567890>> #MUST BE IN eun1-az2
        AdditionalSecurityGroups:
          - <<sg-1234567890>>
          - <<sg-1234567890>>
        PlacementGroup:
          Enabled: true
      ComputeResources:
        - Name: c5n-18xlarge
          InstanceType: c5n.18xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      CustomActions:
        OnNodeConfigured:
          Script: s3://<<YOUR_BUCKET>>/post-install.compute.sh
    - Name: g5
      CapacityType: ONDEMAND
      Networking:
        SubnetIds: 
          - <<subnet-1234567890>> #MUST BE IN eun1-az3
        AdditionalSecurityGroups:
          - <<sg-1234567890>>
          - <<sg-1234567890>>
        PlacementGroup:
          Enabled: true
      ComputeResources:
        - Name: g5-48xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g5.48xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
            GdrSupport: true
        - Name: g5-16xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g5.16xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
            GdrSupport: true
      HealthChecks:
        Gpu:
          Enabled: true
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      CustomActions:
        OnNodeConfigured:
          Script: s3://<<YOUR_BUCKET>>/post-install.compute.sh
    - Name: p5
      CapacityType: ONDEMAND
      Networking:
        SubnetIds: 
          - <<subnet-1234567890>> #MUST BE IN eun1-az3
        AdditionalSecurityGroups:
          - <<sg-1234567890>>
          - <<sg-1234567890>>
        PlacementGroup:
          Enabled: true
      ComputeResources:
        - Name: p5-48xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: p5.48xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
            GdrSupport: true
      HealthChecks:
        Gpu:
          Enabled: true
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      CustomActions:
        OnNodeConfigured:
          Script: s3://<<YOUR_BUCKET>>/post-install.compute.sh
SharedStorage:
  - Name: FsxLustreAZ2
    StorageType: FsxLustre
    MountDir: /fsx
    FsxLustreSettings:
      FileSystemId: <<fs-1234567890>> #MUST BE IN eun1-az2
  - Name: FsxLustre
    StorageType: FsxLustreAZ3
    MountDir: /fsx2
    FsxLustreSettings:
      FileSystemId: <<fs-1234567890>> #MUST BE IN eun1-az3
Monitoring:
  DetailedMonitoring: true
  Logs:
    CloudWatch:
      Enabled: true
      RetentionInDays: 30
      DeletionPolicy: Retain
    Rotation:
      Enabled: true
  Dashboards:
    CloudWatch:
      Enabled: true