Imds:
  ImdsSupport: v2.0
Region: eu-north-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: m6i.2xlarge
  Networking:
    SubnetId: <<subnet-1234567890>>
    AdditionalSecurityGroups:
      - <<sg-1234567890>>
  DisableSimultaneousMultithreading: false
  SharedStorageType: Efs
  LocalStorage:
    RootVolume:
      Size: 100
      Encrypted: true
      VolumeType: gp3
      DeleteOnTermination: true
  CustomActions:
    OnNodeConfigured:
      Script: s3://hpc-benchmarks-software/post-install.headnode.sh
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
    S3Access:
      - BucketName: '*'
        EnableWriteAccess: true
  Imds:
    Secured: True
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
    QueueUpdateStrategy: TERMINATE
    EnableMemoryBasedScheduling: true
  SlurmQueues:
    - Name: g5
      CapacityType: ONDEMAND
      Networking:
        SubnetIds: 
          - <<subnet-1234567890>>
        AdditionalSecurityGroups:
          - <<sg-1234567890>>
        PlacementGroup:
          Enabled: true
      ComputeResources:
        - Name: g5-48xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g5.48xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
            GdrSupport: true
        - Name: g5-16xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: g5.16xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
            GdrSupport: true
      HealthChecks:
        Gpu:
          Enabled: false
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      CustomActions:
        OnNodeConfigured:
          Script: s3://hpc-applications-best-practice/post-install.compute.sh
    - Name: p5
      CapacityType: ONDEMAND
      Networking:
        SubnetIds: 
          - <<subnet-1234567890>>
        AdditionalSecurityGroups:
          - <<sg-1234567890>>
        PlacementGroup:
          Enabled: true
      ComputeResources:
        - Name: p5-48xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: p5.48xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
            GdrSupport: true
      HealthChecks:
        Gpu:
          Enabled: false
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      CustomActions:
        OnNodeConfigured:
          Script: s3://hpc-applications-best-practice/post-install.compute.sh
    - Name: p5-spot
      CapacityType: SPOT
      Networking:
        SubnetIds: 
          - <<subnet-1234567890>>
        AdditionalSecurityGroups:
          - <<sg-1234567890>>
        PlacementGroup:
          Enabled: true
      ComputeResources:
        - Name: p5-48xlarge
          DisableSimultaneousMultithreading: true
          InstanceType: p5.48xlarge
          MinCount: 0
          MaxCount: 200
          Efa:
            Enabled: true
            GdrSupport: true
      HealthChecks:
        Gpu:
          Enabled: false
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::aws:policy/SecretsManagerReadWrite
        S3Access:
          - BucketName: '*'
            EnableWriteAccess: true
      CustomActions:
        OnNodeConfigured:
          Script: s3://hpc-applications-best-practice/post-install.compute.sh          
SharedStorage:
  - Name: FsxLustre
    StorageType: FsxLustre
    MountDir: /fsx
    FsxLustreSettings:
      FileSystemId: <<fs-1234567890>>
Monitoring:
  DetailedMonitoring: true
  Logs:
    CloudWatch:
      Enabled: true
      RetentionInDays: 30
      DeletionPolicy: Retain
    Rotation:
      Enabled: true
  Dashboards:
    CloudWatch:
      Enabled: true