"""Property-based tests for the WRF step-timing helper.

apps/WRF/lib/wrf-step-timing.sh gives the WRF benchmark scripts two values
next to the average step of rsl.error.0000: the median of every
"Timing for main" step, and the steady step, the mean of every step but the
first and those that follow a "Timing for Writing" line (history, restart) or
a "Timing for processing" line (lateral boundaries, wrfinput). The rule
assumes a single domain, and WRF prints no timing line for auxiliary input
streams (auxinput*, such as SST updates), so steps that read them are not
left out.

Unlike the other suites here, which re-implement shell logic in Python, these
tests run the bash helper itself, the way the scripts call it, on
rsl.error.0000 files generated by Hypothesis (synthetic times only), and
compare it with the reference below. They also run the WRF shell suite
(apps/WRF/tests/run-tests.sh: the checked-in fixtures and every benchmark
script end to end with stubs), so a single `pytest tests` covers it.

Run with:
    python -m pip install -r tests/requirements.txt
    python -m pytest tests/test_wrf_step_timing.py -q
"""
from __future__ import annotations

import shutil
import statistics
import subprocess
import tempfile
from pathlib import Path

import pytest
from hypothesis import given, settings, strategies as st

REPO = Path(__file__).resolve().parents[1]
LIB = REPO / "apps" / "WRF" / "lib" / "wrf-step-timing.sh"
SHELL_SUITE = REPO / "apps" / "WRF" / "tests" / "run-tests.sh"

pytestmark = pytest.mark.skipif(shutil.which("bash") is None, reason="needs bash")

# The I/O lines WRF prints, as the helper must recognise them.
IO_LINES = {
    "history": "Timing for Writing wrfout_d01_2000-01-01_00:00:00 for domain        1:    3.00000 elapsed seconds",
    "restart": "Timing for Writing restart for domain        1:    4.00000 elapsed seconds",
    "boundary": "Timing for processing lateral boundary for domain        1:    0.50000 elapsed seconds",
    "wrfinput": "Timing for processing wrfinput file (stream 0) for domain        1:    2.00000 elapsed seconds",
}
# Lines that are neither a step nor I/O, and must change nothing.
OTHER_LINES = (
    "d01 2000-01-01_00:00:00  Input data is acceptable to use: wrfbdy_d01",
    " Ntasks in X            2 , ntasks in Y            4",
    "WRF V4.6.1 MODEL",
)
# A step, as WRF prints it with a fixed or with an adaptive time step.
STEP_KINDS = ("step", "adaptive-step")


def seconds(k: int) -> str:
    """A step time of k hundred-thousandths of a second, as WRF prints it (5 decimals)."""
    return f"{k // 100_000}.{k % 100_000:05d}"


def render(events: list[tuple[str, object]]) -> str:
    """Write the events as the lines of an rsl.error.0000."""
    lines, n = [], 0
    for kind, value in events:
        if kind in STEP_KINDS:
            n += 1
            # With an adaptive time step WRF labels the step "main (dt= 15.00)",
            # so its time is the 11th field, not the 9th AVG_STEP reads.
            label = "main (dt= 15.00)" if kind == "adaptive-step" else "main"
            lines.append(f"Timing for {label}: time 2000-01-01_00:{n // 60:02d}:{n % 60:02d}"
                         f" on domain   1: {seconds(value):>10} elapsed seconds")
        elif kind == "io":
            lines.append(IO_LINES[value])
        else:
            lines.append(value)
    return "".join(line + "\n" for line in lines)


def reference(events: list[tuple[str, object]]) -> tuple[str, str]:
    """(median, steady step) as the helper documents them, or N/A."""
    steps = [float(seconds(v)) for kind, v in events if kind in STEP_KINDS]
    median = f"{statistics.median(steps):.5f}" if steps else "N/A"
    total, count, n, after_io = 0.0, 0, 0, False
    for kind, value in events:
        if kind == "io":
            after_io = True
        elif kind in STEP_KINDS:
            n += 1
            if n > 1 and not after_io:
                total += float(seconds(value))
                count += 1
            after_io = False
    steady = f"{total / count:.5f}" if count else "N/A"
    return median, steady


def helper(path: Path) -> tuple[str, str]:
    """Run the bash helper as the benchmark scripts do, under set -euo pipefail."""
    result = subprocess.run(
        ["bash", "-c", 'set -euo pipefail; . "$1"; wrf_median_step "$2"; wrf_steady_step "$2"',
         "_", str(LIB), str(path)],
        capture_output=True, text=True, check=True)
    median, steady = result.stdout.splitlines()
    return median, steady


# Times under 10 s mixed with longer ones, so a text sort ("10.0" < "9.0")
# and a numeric sort often disagree. Each step is printed in either of WRF's
# two formats (fixed or adaptive time step).
steps = st.tuples(st.sampled_from(STEP_KINDS),
                  st.one_of(st.integers(min_value=0, max_value=999_999),
                            st.integers(min_value=1_000_000, max_value=99_999_999)))
io = st.sampled_from(sorted(IO_LINES)).map(lambda name: ("io", name))
other = st.sampled_from(OTHER_LINES).map(lambda line: ("other", line))
logs = st.lists(st.one_of(steps, steps, io, other), max_size=60)


@settings(max_examples=200)
@given(events=logs)
def test_helper_matches_reference(events):
    """Median and steady step agree with the reference on any mix of steps and I/O."""
    with tempfile.TemporaryDirectory() as tmp:
        rsl = Path(tmp) / "rsl.error.0000"
        rsl.write_text(render(events))
        assert helper(rsl) == reference(events)


@settings(max_examples=100)
@given(events=logs, trailing=st.lists(st.one_of(io, other), min_size=1, max_size=5))
def test_io_after_the_last_step_changes_nothing(events, trailing):
    """The last history write comes after the last step: it must not count."""
    with tempfile.TemporaryDirectory() as tmp:
        before, after = Path(tmp) / "before", Path(tmp) / "after"
        before.write_text(render(events))
        after.write_text(render(events + trailing))
        assert helper(after) == helper(before)


def test_wrf_shell_suite_passes():
    """apps/WRF/tests/run-tests.sh: the fixtures, and every benchmark script end to end."""
    result = subprocess.run(["bash", str(SHELL_SUITE)], capture_output=True, text=True)
    assert result.returncode == 0, result.stdout[-6000:] + result.stderr[-2000:]
